#!/bin/bash
#PBS -l nodes=1:ppn=2,walltime=4:00:00,vmem=20gb
#PBS -N pRF

set -e
set -x

# grab important input configs
fsdir=`jq -r '.freesurfer' config.json`
template=`jq -r '.template' config.json`	

# make local copy of freesurfer directory
[ ! -d output ] && cp -LR ${fsdir} output && chmod -R +w  ./output/*

# fit benson predicted prf based purely on anatomy: templates can be eitehr benson17 or benson14 
[ ! -f ./output/mri/benson14_eccen.nii.gz ] && singularity exec -e  docker://nben/neuropythy:0.12.6 \
	python -m neuropythy benson14_retinotopy \
	--verbose ${fsdir} \
	--vol-format=nii.gz \
	--template=${template}

# make output directories and clean up
[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt
time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:7.1.1 ./benson2bl.sh

if [ ! -f prf/prf_surfaces/rh.r2 ]; then
	echo "creating binary surface files of visual vertices for visualizer"
	time singularity exec -e docker://brainlife/dipy:1.4.0 python3 ./create_R2.py ./prf/prf_surfaces/rh.varea ./prf/prf_surfaces/lh.varea
fi

	
