#!/bin/bash
#PBS -l nodes=1:ppn=2,walltime=4:00:00,vmem=20gb
#PBS -N pRF

set -e
set -x

fsdir=$(jq -r '.freesurfer' config.json)
template=$(jq -r '.template' config.json)

# make local copy of freesurfer directory
[ ! -d output ] && cp -LR "${fsdir}" output && chmod -R +w ./output/*

APPTAINERENV_SUBJECT="$PWD/output"
singularity exec -e docker://brainlife/neuropythy:0.12.16  \
        python -m neuropythy benson14_retinotopy \
        --verbose --template ${template}  \
        --vol-format=nii.gz \
        ${APPTAINERENV_SUBJECT}

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1
echo "$FREESURFER_LICENSE" > license.txt
time singularity exec -e -B "$(pwd)/license.txt:/usr/local/freesurfer/license.txt" docker://brainlife/freesurfer:7.1.1 ./benson2bl.sh

if [ ! -f prf/prf_surfaces/rh.r2 ]; then
    echo "creating binary surface files of visual vertices for visualizer"
    time singularity exec -e docker://brainlife/dipy:1.4.0 python3 ./create_R2.py ./prf/prf_surfaces/rh.varea ./prf/prf_surfaces/lh.varea
fi
